name: CI pipeline

# Defines when to trigger this workflow
on:
  # When pushing commit(s) to master or adding any tag(s).
  push:
    branches: [ master ]
    tags: [ '**' ]
  # When submiting pull request to master.
  pull_request:
    branches: [ master ]
    tags: [ '**' ]
  # Every Monday, 1:00 am (UTC).
  schedule:
    - cron: '0 1 * * 1'

# Defines all jobs to be run in parallel.
jobs:
  # See https://help.github.com/en/actions/language-and-framework-guides/github-actions-for-javascript-and-typescript
  hexo-generate:
    name: Generate site on Node ${{ matrix.node }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [10.x, 12.x, 13.x]
    steps:
      # See https://github.com/actions/checkout
      - name: Download the repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50
          submodules: true
      # See https://github.com/actions/setup-node
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      # See https://github.com/actions/cache
      - name: Cache NPM packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      # See https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
      - name: Install dependencies
        run: npm install
      # See https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
      - name: Generate Hexo site
        run: ./node_modules/hexo-cli/bin/hexo generate

  # See https://help.github.com/en/actions/language-and-framework-guides
  validate-links:
    name: Validate links in README.md
    runs-on: ubuntu-20.04
    steps:
      # See https://github.com/actions/checkout
      - name: Download the repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50
          submodules: true
      # See https://github.com/actions/setup-ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.7
      # See https://github.com/actions/setup-ruby
      - name: Install awesome_bot
        run: gem install awesome_bot
      # See https://github.com/dkhamsing/awesome_bot
      - name: Validate links in Markdown
        run: awesome_bot README.md --allow-dupe --allow-redirect --allow 429 -w localhost --skip-save-results
